apiVersion: k8sproxy.app-scape.de/v1alpha1
kind: ProxyEntry
metadata:
  labels:
    app.kubernetes.io/name: k8s-proxy-new
    app.kubernetes.io/managed-by: kustomize
  name: proxyentry-sample
spec:
  # TODO(user): Add fields here
